name: Auto Convert Rules

on:
  push:
    paths:
      - 'rules/**/*.list'
      - '*.list'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run Converter Script
        run: python generate_yaml.py

      - name: Commit & Push Generated Rules
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "auto: update direct/proxy list & yaml [skip ci]"
          file_pattern: "generated/*"
          branch: ${{ github.ref_name }}
